name: Deploy backend to AWS EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/hubber/src/backend
            pm2 stop app.js
            cd /home/ubuntu/hubber/
            git pull origin main
            cd /home/ubuntu/hubber/src/backend
            npm install
            pm2 start app.js